// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

namespace boba
{
/**
 * @brief Performs the recurrent Phi (or Psi) matrix computation
 * Used part of method from amen_solve2, see https://github.com/oseledets/TT-Toolbox/blob/40d0d9dbef4195155be52730d4f30ca2ecf7b74e/solve/amen_solve2.m#L834
 * @return a tuple of Phi_out and its norm, phi_norm
 */

template <size_t dimension, execution_space space, typename data_t>
std::pair<::boba::Tensor<3, space, data_t>, data_t> compute_next_Phi(
  const ::boba::Tensor<3, space, data_t>& Phi_prev,
  const ::boba::Tensor<3, space, data_t>& x,
  const ::boba::Tensor<4, space, data_t>& A_core,
  const ::boba::Tensor<3, space, data_t>& y,
  bool sweep_left_right,
  data_t external_norm)
{
  BOBA_CALI_MARK
  ::boba::Tensor<3, space, data_t> Phi_out;

  if (sweep_left_right)
  {
    checkpoint();
    auto xPhi = tensor_contraction<1>(
      {"rx1", "row", "rx2"}, x, {"rx1", "ry1", "ra1"}, Phi_prev, {"row", "rx2", "ry1", "ra1"});

    checkpoint();
    auto AxPhi = tensor_contraction<2>(
      {"ra1", "row", "col", "ra2"}, A_core, {"row", "rx2", "ry1", "ra1"}, xPhi, {"col", "ra2", "rx2", "ry1"});

    checkpoint();
    Phi_out = tensor_contraction<2>(
      {"col", "ra2", "rx2", "ry1"}, AxPhi, {"ry1", "col", "ry2"}, y, {"rx2", "ry2", "ra2"}); // Note that in a left-to-right sweep, the index ordering is {rx, ry, ra}
  }
  else
  {
    checkpoint();
    auto Phi_new = ::boba::tensor_contraction<1>(
      {"ry1", "col", "ry2"}, y, {"ry2", "ra2", "rx2"}, Phi_prev, {"ry1", "col", "ra2", "rx2"});

    checkpoint();
    auto Phi_new_new = ::boba::tensor_contraction<2>(
      {"ra1", "row", "col", "ra2"}, A_core, {"ry1", "col", "ra2", "rx2"}, Phi_new, {"ra1", "row", "ry1", "rx2"});

    checkpoint();
    Phi_out = ::boba::tensor_contraction<2>(
      {"ra1", "row", "ry1", "rx2"}, Phi_new_new, {"rx1", "row", "rx2"}, x, {"ry1", "ra1", "rx1"}); // In contrast, for a right-to-left sweep, the index ordering is {ry, ra, rx}
  }

  // Extract the scale to prevent overload
  data_t phi_norm = 0.0;
  if (external_norm > 0.0)
  {
    Phi_out *= 1.0 / external_norm;
  }
  else
  {
    phi_norm = ::boba::norm_frobenius(Phi_out);
    if (phi_norm > 10.0 * boba::epsilon<data_t>())
    {
      Phi_out *= 1.0 / phi_norm;
    }
    else
    {
      phi_norm = 1.0;
    }
  }

  checkpoint();
  return std::make_pair(Phi_out, phi_norm);
}

/**
 * @brief Performs the recurrent Phi (or Psi) matrix computation, when the operator is the identity
 * @return a tuple of Phi_out and its norm, phi_norm
 */

template <size_t dimension, execution_space space, typename data_t>
std::tuple<::boba::Tensor<3, space, data_t>, data_t> compute_next_Phi(
  ::boba::Tensor<3, space, data_t> Phi_prev,
  ::boba::Tensor<3, space, data_t> x,
  ::boba::Tensor<3, space, data_t> y,
  bool sweep_left_right,
  data_t external_norm)
{
  BOBA_CALI_MARK
  auto rows = x.sizes(1);
  auto cols = y.sizes(1);
  ::boba::Tensor<4, space, data_t> A_core({1, rows, cols, 1});
  ::boba::set_to_identity_core(A_core);

  return compute_next_Phi<dimension>(Phi_prev, x, A_core, y, sweep_left_right, external_norm);
}

/**
 * \brief Port of bfun3 method found in amen_solve2
 * See https://github.com/oseledets/TT-Toolbox/blob/40d0d9dbef4195155be52730d4f30ca2ecf7b74e/solve/amen_solve2.m#L924
 */

template <::boba::execution_space space, typename data_t>
boba::Tensor<3, space, data_t> bfun3(
  const boba::Tensor<3, space, data_t>& Phi1,
  const boba::Tensor<4, space, data_t>& A,
  const boba::Tensor<3, space, data_t>& Phi2,
  const boba::Tensor<3, space, data_t>& x)
{
  BOBA_CALI_MARK
  checkpoint();

  auto xPhi2 = boba::tensor_contraction<1>(
    {"rx1", "m", "rx2"}, x, {"rx2", "ra2", "ry2"}, Phi2, {"rx1", "m", "ra2", "ry2"});

  checkpoint();
  auto AxPhi2 = boba::tensor_contraction<2>(
    {"ra1", "n", "m", "ra2"}, A, {"rx1", "m", "ra2", "ry2"}, xPhi2, {"ra1", "n", "rx1", "ry2"});

  checkpoint();
  auto Phi1AxPhi2 = boba::tensor_contraction<2>(
    {"ry1", "rx1", "ra1"}, Phi1, {"ra1", "n", "rx1", "ry2"}, AxPhi2, {"ry1", "n", "ry2"});

  return Phi1AxPhi2;
}

/*
  bfun3 (2-site DMRG version)
*/
template <::boba::execution_space space, typename data_t>
boba::Vector<space, data_t> bfun3(
  const boba::Tensor<3, space, data_t>& Phi1,
  const boba::Tensor<4, space, data_t>& B1,
  const boba::Tensor<4, space, data_t>& B2,
  const boba::Tensor<3, space, data_t>& Phi2,
  const boba::Tensor<4, space, data_t>& x)
{
  BOBA_CALI_MARK

  checkpoint();
  auto Phi1x = boba::tensor_contraction<1>(
    {"rx1", "ry1", "rb1"}, Phi1, // Phi1 was generated by a left-to-right sweep, so the index ordering is {rx, ry, rb}
    {"rx1", "m1", "m2", "rx3"},
    x,
    {"ry1", "rb1", "m1", "m2", "rx3"});

  checkpoint();
  auto B1Phi1x = boba::tensor_contraction<2>(
    {"rb1", "k1", "m1", "rb2"}, B1, {"ry1", "rb1", "m1", "m2", "rx3"}, Phi1x, {"k1", "rb2", "ry1", "m2", "rx3"});

  checkpoint();
  auto B2B1Phi1x = boba::tensor_contraction<2>(
    {"rb2", "k2", "m2", "rb3"}, B2, {"k1", "rb2", "ry1", "m2", "rx3"}, B1Phi1x, {"k2", "rb3", "k1", "ry1", "rx3"});

  checkpoint();
  auto Phi2B2B1Phi1x = boba::tensor_contraction<2>(
    {"ry3", "rb3", "rx3"}, Phi2, // Phi2 was generated by a right-to-left sweep, so the index ordering is {ry, rb, rx}
    {"k2", "rb3", "k1", "ry1", "rx3"},
    B2B1Phi1x,
    {"ry1", "k1", "k2", "ry3"});

  auto y = flatten(Phi2B2B1Phi1x);
  return y;
}

/**
 * @brief Creates a matrix M such that M*reshape(x) = Phi1*A*Phi2*x
 * @return A matrix that corresponds to the action of Phi1*A*Phi2
 */
template <::boba::execution_space space, typename data_t>
boba::Matrix<space, data_t> bfun3_matrix(
  const boba::Tensor<3, space, data_t>& Phi1,
  const boba::Tensor<4, space, data_t>& A,
  const boba::Tensor<3, space, data_t>& Phi2)
{
  BOBA_CALI_MARK
  checkpoint();

  // \sum\limits_{rx1, ra1}\sum\limits_{m, ra2}\sum\limits_{rx2} Phi1(ry1, rx1, ra1) * A(ra1, n, m, ra2) * x(rx1, m, rx2) * Phi2(rx2, ra2, ry2)
  // Matrix is
  // \sum\limits_{ra1}\sum\limits_{ra2} Phi1(ry1, rx1, ra1) * A(ra1, n, m, ra2) * Phi2(rx2, ra2, ry2)

  checkpoint();
  auto Phi1A = boba::tensor_contraction<1>(
    {"ry1", "rx1", "ra1"}, Phi1, {"ra1", "row", "col", "ra2"}, A, {"ry1", "rx1", "row", "col", "ra2"});

  checkpoint();
  auto Phi1APhi2 = boba::tensor_contraction<1>(
    {"ry1", "rx1", "row", "col", "ra2"}, Phi1A, {"rx2", "ra2", "ry2"}, Phi2, {"ry1", "row", "ry2", "rx1", "col", "rx2"});

  // need (ry1, row ry2) by (rx1, col, rx2)
  auto rows = Phi1APhi2.sizes(0) * Phi1APhi2.sizes(1) * Phi1APhi2.sizes(2);
  auto cols = Phi1APhi2.sizes(3) * Phi1APhi2.sizes(4) * Phi1APhi2.sizes(5);

  return reshape_to_matrix(Phi1APhi2, {rows, cols});
}

/*
 * @brief A helper struct corresponding to the operator needed by to solve3d_2ml
 */

template <::boba::execution_space space, typename data_t>
struct Solve3D2MLGMRESOperator
{
  boba::Tensor<3, space, data_t> Phi1;
  boba::Tensor<4, space, data_t> A;
  boba::Tensor<3, space, data_t> Phi2;

  [[nodiscard]]
  auto operator*(boba::Tensor<3, space, data_t> const& x) const
  {
    BOBA_CALI_MARK
    auto bfun_x = bfun3(Phi1, A, Phi2, x);
    return bfun_x;
  }
};

template <typename data_t>
struct Solve3D2MLOptions
{
  size_t method = 0;
  data_t tolerance_relative = 1.0e-60;
  data_t tolerance_absolute = 1.0e-60;
  index_t outer_iterations = 40;
  index_t inner_iterations = 200;
};

/**
 * @brief An iterative solver routine that iteratively solves Phi1*A*Phi2*x = y
 * See https://github.com/oseledets/TT-Toolbox/blob/master/solve/solve3d_2ml.m
 */

template <::boba::execution_space space, typename data_t>
boba::Tensor<3, space, data_t> solve3d_2ml(
  const boba::Tensor<3, space, data_t>& Phi1,
  const boba::Tensor<4, space, data_t>& A,
  const boba::Tensor<3, space, data_t>& Phi2,
  const boba::Tensor<3, space, data_t>& y,
  data_t tol,
  const boba::Tensor<3, space, data_t>& x0,
  Solve3D2MLOptions<data_t> options)
{
  BOBA_CALI_MARK
  checkpoint();
  auto dy = y - bfun3(Phi1, A, Phi2, x0);

  auto norm_dy = ::boba::norm_frobenius(dy);
  auto real_tol = tol / norm_dy;
  auto x = x0;

  if (space != host_space)
  {
    options.method = 1;
  }

  if (real_tol < 1.0)
  {
    // Instantiate solver with your options
    switch (options.method)
    {
    case 0: // Using Eigen GMRES
    {
      auto x0_vector_norm = ::boba::norm_frobenius(x0);
      auto dy_vector = flatten(dy);
      auto bfun_operator = bfun3_matrix(Phi1, A, Phi2);

      auto dx = detail::eigen_gmres(bfun_operator, dy_vector, options.tolerance_relative * x0_vector_norm, 30_z);

      checkpoint();
      auto dx_tensor = reshape<3>(dx, x.sizes());
      x += dx_tensor; // x = x0 + dx
      break;
    }
    case 1: // BoBa GMRES
    {
      using operator_t = Matrix<space, data_t>;
      using vector_t = Vector<space, data_t>;
      Krylov<operator_t, vector_t> solver(
        options.outer_iterations,
        options.inner_iterations,
        real_tol);

      checkpoint();
      auto bfun_operator = bfun3_matrix(Phi1, A, Phi2);
      checkpoint();
      solver.method = boba::KrylovMethods::gmres;
      solver.set_matrix(bfun_operator);
      solver.verbose = false;
      solver.relative_threshold = options.tolerance_relative;
      solver.absolute_threshold = options.tolerance_absolute;

      checkpoint();
      auto dy_vector = flatten(dy);
      vector_t dx(dy_vector.sizes());
      dx.fill_with_zeros();

      checkpoint();
      solver.solve(dy_vector, dx, dx);

      checkpoint();
      auto dx_tensor = reshape<3>(dx, x.sizes());
      x += dx_tensor; // x = x0 + dx
      break;
    }
    case 2:
    {
      using operator_t = Solve3D2MLGMRESOperator<space, data_t>;
      using vector_t = Tensor<3, space, data_t>;
      Krylov<operator_t, vector_t> solver(
        options.outer_iterations,
        options.inner_iterations,
        real_tol);

      checkpoint();
      operator_t bfun_operator;
      bfun_operator.Phi1 = Phi1;
      bfun_operator.A = A;
      bfun_operator.Phi2 = Phi2;

      checkpoint();
      solver.method = boba::KrylovMethods::gmres;
      solver.set_matrix(bfun_operator);
      solver.verbose = false;
      solver.relative_threshold = options.tolerance_relative;
      solver.absolute_threshold = options.tolerance_absolute;

      checkpoint();
      vector_t dx(x0.sizes());
      dx.fill_with_zeros();

      checkpoint();
      solver.solve(dy, dx, dx);

      checkpoint();
      x += dx; // x = x0 + dx
      break;
    }
    default:
    {
      boba_assert_le(options.method, 2, "Invalid choice of options.method");
    }
    }
  }

  checkpoint();
  return x;
}

} // namespace boba
