// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

namespace boba
{

template <typename data_t>
struct TensorTrainDMRG
{
  /*
    This class is a reimplements Oseledets' dmrg_solve3 using the BoBa framework
    See https://github.com/oseledets/TT-Toolbox/blob/master/solve/dmrg_solve3.m
  */

  data_t convergence_tolerance = 1.0e-10;
  index_t kickrank = 4;
  data_t resid_damp = 2.0; // Truncation error to true residual treshold
  index_t max_direct_solve_size = 1500;
  index_t max_allowed_ranks = 1000;

  Solve3D2MLOptions<data_t> solve3d_2ml_options;

  template <typename unsupported_operator, typename unsupported_vector>
  unsupported_vector solve(
    const unsupported_operator& crA,
    const unsupported_vector& cry,
    const unsupported_vector& tt_initial_guess)
  {
    detail::ignore(crA, tt_initial_guess);
    boba_error("DMRG not yet supported for this operator/vector combination.");
    return cry;
  }

  template <size_t dimension, execution_space space>
  ::boba::TensorTrain<dimension, host_space, data_t> solve(
    const ::boba::TensorTrainMatrix<dimension, space, data_t>& crA,
    const ::boba::TensorTrain<dimension, space, data_t>& cry,
    const ::boba::TensorTrain<dimension, space, data_t>& tt_initial_guess,
    const bool verb = false)
  {
    BOBA_CALI_MARK
    checkpoint();

    auto crx = tt_initial_guess;

    checkpoint();
    ::boba::TensorTrain<dimension + 1, space, data_t> phia(::boba::filled_array<dimension + 1>(1_z));
    ::boba::TensorTrain<dimension + 1, space, data_t> phiy(::boba::filled_array<dimension + 1>(1_z));
    phia.fill_with(1.0);
    phiy.fill_with(1.0);

    boba_always_assert_equal(crA.core_rows(), crA.core_cols(), "To use DMRG with rectangular systems, first form the normal equations  A^TAx = A^Tb and solve that system instead.");

    data_t step_dpow = 0.1; // stepsize for d-power in truncations
    data_t min_dpow = 1;    // Minimal d-power for truncations
    const index_t step_drank = 1;

    data_t bot_conv = 0.1;  // bottom convergence factor - if better, we can decrease dpow and drank
    data_t top_conv = 0.99; // top convergence factor - if worse, we have to increase dpow and drank

    size_t nswp = 20;

    size_t rmax = 1000;
    int dirfilter = 0; // both

    data_t res_new;
    data_t res_prev;
    kickrank = 2;
    int flg;
    size_t iter = 0;

    checkpoint();
    // Orthogonalization
    for (size_t corp1 = dimension; corp1 > 1; corp1--)
    {
      auto cor = corp1 - 1;
      {
        auto cr_mat = compute_unfold_right(crx.cores[cor]).transpose();
        QR<space, data_t> qr;
        qr(cr_mat);

        crx.cores[cor] = reshape<3>(qr.Q, {qr.Q.cols(), crx.sizes(cor), crx.ranks(cor + 1)});

        auto cr2 = tensor_contraction_single_index(
          {"rxim1", "n", "rxi"}, crx.cores[cor - 1], {"rxinew", "rxi"}, qr.R, {"rxim1", "n", "rxinew"});

        crx.cores[cor - 1] = reshape<3>(cr2, {crx.ranks(cor - 1), crx.sizes(cor - 1), crx.ranks(cor)});
      }

      checkpoint();
      std::tie(phia.cores[cor], std::ignore) = compute_next_Phi<dimension>(phia.cores[cor + 1], crx.cores[cor], crA.cores[cor], crx.cores[cor], false, 1.0);
      std::tie(phiy.cores[cor], std::ignore) = compute_next_Phi<dimension>(phiy.cores[cor + 1], crx.cores[cor], cry.cores[cor], false, 1.0);
    }

    bool last_sweep = false;
    size_t swp = 1;
    size_t cor = 0;

    auto dx_old = filled_array<dimension, data_t>(1.0);
    auto dx = filled_array<dimension, data_t>(0.0);
    data_t max_res = 0.0;
    data_t max_dx = 0.0;
    index_t max_iter = 0;
    // For extra-rank addition
    auto dpows = filled_array<dimension, data_t>(1.0) * min_dpow;
    auto dranks = filled_array<dimension, index_t>(0_z);
    int dir = 1;

    // DMRG sweeps
    while (swp <= nswp)
    {
      // Extract elements - matrix
      checkpoint();
      auto phiycry = tensor_contraction_single_index(
        {"rx", "ryi", "one"}, phiy.cores[cor], // phiy.cores[cor] was generated by a left-to-right sweep, so the index ordering is {rx, ry, rb}
        {"ryi", "n", "ryip1"},
        cry.cores[cor],
        {"rx", "one", "n", "ryip1"});

      checkpoint();
      auto phiycrycry = tensor_contraction_single_index(
        {"rx", "one", "n", "ryip1"}, phiycry, {"ryip1", "nip1", "ryip2"}, cry.cores[cor + 1], {"rx", "one", "n", "nip1", "ryip2"});

      checkpoint();
      auto phiycrycryphiy = tensor_contraction_single_index(
        {"rx", "one", "n", "nip1", "ryip2"}, phiycrycry, {"ryip2", "_one", "r?"}, phiy.cores[cor + 2], {"rx", "one", "n", "nip1", "_one", "r?"});

      const auto rhs = reshape<4>(phiycrycryphiy, {phiycrycryphiy.sizes(0), phiycrycryphiy.sizes(2), phiycrycryphiy.sizes(3), phiycrycryphiy.sizes(5)});
      auto rhs_flat = flatten(phiycrycryphiy);

      const auto norm_rhs = ::boba::norm_frobenius(rhs);

      // sol_prev
      auto sol_prev_tensor = tensor_contraction_single_index(
        {"crxi", "ni", "crxi+1"}, crx.cores[cor], {"crxi+1", "ni+1", "crxi+2"}, crx.cores[cor + 1], {"crxi", "ni", "ni+1", "crxi+2"});

      auto sol_prev = flatten(sol_prev_tensor);

      auto tol_pow = pow(static_cast<data_t>(dimension), static_cast<data_t>(dpows[cor]));
      auto real_tol = (convergence_tolerance / tol_pow) / resid_damp;
      if (last_sweep)
      {
        real_tol = (convergence_tolerance / sqrt(static_cast<data_t>(dimension))) / resid_damp;
      }

      checkpoint();
      auto Phi1 = phia.cores[cor];
      auto Phi2 = phia.cores[cor + 2];
      auto A1 = crA.cores[cor];
      auto A2 = crA.cores[cor + 1];
      boba::Vector<space, data_t> sol;
      boba::Matrix<space, data_t> B;

      if (crx.ranks(cor) * crx.sizes(cor) * crx.sizes(cor + 1) * crx.ranks(cor + 2) < max_direct_solve_size)
      {
        checkpoint();
        // Direct solution
        //       |     |    |     |
        //  B = Phi1 - A1 - A2 - Phi2
        //       |     |    |     |
        if ((dir + dirfilter) != 0)
        {
          auto Phi1A1 = tensor_contraction_single_index(
            {
              "rxi",
              "_rxi",
              "rai",
            },
            Phi1, // Phi1 was generated by a left-to-right sweep, so the index ordering is {rx, ry, ra}
            {"rai", "ni", "_ni", "rai+1"},
            A1,
            {"_rxi", "ni", "rai+1", "rxi", "_ni"});

          checkpoint();
          auto Phi1A1A2 = tensor_contraction_single_index(
            {"_rxi", "ni", "rai+1", "rxi", "_ni"}, Phi1A1, {"rai+1", "ni+1", "_ni+1", "rai+2"}, A2, {"_rxi", "ni", "ni+1", "rai+2", "rxi", "_ni", "_ni+1"});

          checkpoint();
          auto Phi1A1A2Phi2 = tensor_contraction_single_index(
            {"_rxi", "ni", "ni+1", "rai+2", "rxi", "_ni", "_ni+1"}, Phi1A1A2, {"_rxi+2", "rai+2", "rxi+2"}, Phi2, // Phi2 was generated by a right-to-left sweep, so the index ordering is {ry, rb, rx}
            {"_rxi", "ni", "ni+1", "_rxi+2", "rxi", "_ni", "_ni+1", "rxi+2"});

          auto B_rows = crx.ranks(cor) * crx.sizes(cor) * crx.sizes(cor + 1) * crx.ranks(cor + 2);
          auto B_cols = crx.ranks(cor) * crx.sizes(cor) * crx.sizes(cor + 1) * crx.ranks(cor + 2);
          B.resize({B_rows, B_cols});
          B.reshape(Phi1A1A2Phi2);
        }

        res_prev = norm_difference_frobenius(bfun3(Phi1, A1, A2, Phi2, sol_prev_tensor), rhs_flat) / norm_rhs;
        data_t res_prev_alt = norm_difference_frobenius(B * sol_prev, rhs_flat) / norm_rhs;

        checkpoint();
        if ((res_prev > real_tol) and ((dir + dirfilter) != 0))
        {
          sol = backsolve(B, rhs_flat);
          flg = 0;
          res_new = norm_difference_frobenius(B * sol, rhs_flat) / norm_rhs;
          iter = 1;
        }
        else
        {
          sol = flatten(sol_prev_tensor);
          res_new = res_prev;
          flg = 0;
          iter = 0;
        }
      }
      else // Structured solution.
      {
        checkpoint();
        res_prev = norm_difference_frobenius(bfun3(Phi1, A1, A2, Phi2, sol_prev_tensor), rhs_flat) / norm_rhs;

        if ((res_prev > real_tol) and ((dir + dirfilter) != 0))
        {
          // Since we only have procedures for 3 blocks, we have to
          // merge two of them. Usually this is not a serious overhead... on those problems where DMRG works in principle
          Tensor<3, space, data_t> Phi1mex;
          Tensor<3, space, data_t> Phi2mex;
          Tensor<4, space, data_t> Amex;

          if (crx.ranks(cor) * crx.sizes(cor) <= min(crx.sizes(cor) * crx.sizes(cor + 1), crx.sizes(cor + 1) * crx.ranks(cor + 2)))
          {
            checkpoint();
            auto Phi1A1 = tensor_contraction_single_index(
              {
                "rxi",
                "_rxi",
                "rai",
              },
              Phi1, // Phi1 was generated by a left-to-right sweep, so the index ordering is {rx, ry, ra}
              {"rai", "ni", "_ni", "rai+1"},
              A1,
              {"_rxi", "ni", "rxi", "_ni", "rai+1"});

            checkpoint();
            Phi1mex = reshape<3>(Phi1A1, {Phi1A1.sizes(0) * Phi1A1.sizes(1), Phi1A1.sizes(2) * Phi1A1.sizes(3), Phi1A1.sizes(4)});

            Amex = A2;

            Phi2mex = Phi2;
            checkpoint();
            boba::permute(
              {"a", "b", "c"},
              Phi2mex,
              {"c", "b", "a"});
          }
          else if (crx.sizes(cor) * crx.sizes(cor + 1) <= min(crx.ranks(cor) * crx.sizes(cor), crx.sizes(cor + 1) * crx.ranks(cor + 2)))
          {
            checkpoint();
            auto A1A2 = tensor_contraction_single_index(
              {"rai", "crxi", "crxi+1", "rai+1"}, A1, {"rai+1", "crxi+2", "crxi+3", "rai+2"}, A2, {"rai", "crxi", "crxi+2", "crxi+1", "crxi+3", "rai+2"});

            Amex = reshape<4>(A1A2, {A1A2.sizes(0), A1A2.sizes(1) * A1A2.sizes(2), A1A2.sizes(3) * A1A2.sizes(4), A1A2.sizes(5)});

            Phi1mex = Phi1;
            boba::permute(
              {"a", "b", "c"},
              Phi1mex,
              {"b", "a", "c"});

            Phi2mex = Phi2;
            boba::permute(
              {"a", "b", "c"},
              Phi2mex,
              {"c", "b", "a"});
          }
          else
          {
            checkpoint();
            Phi1mex = Phi1;
            boba::permute(
              {"a", "b", "c"},
              Phi1mex,
              {"b", "a", "c"});

            Amex = A1;

            auto A2Phi2 = tensor_contraction_single_index(
              {"rai+1", "ni", "ni+1", "rai+2"}, A2, {"crxi+2", "rai+2", "crxi+3"}, Phi2, {"ni", "crxi+2", "rai+1", "ni+1", "crxi+3"});

            checkpoint();
            Phi2mex = reshape<3>(A2Phi2, {A2Phi2.sizes(0) * A2Phi2.sizes(1), A2Phi2.sizes(2), A2Phi2.sizes(3) * A2Phi2.sizes(4)});
          }

          checkpoint();
          auto rhsmex = reshape<3>(rhs, {Phi1mex.sizes(0), Amex.sizes(1), Phi2mex.sizes(2)});
          auto sol_prev_max = reshape<3>(sol_prev, {Phi1mex.sizes(0), Amex.sizes(1), Phi2mex.sizes(2)});

          auto solve3d_2ml_options_local = solve3d_2ml_options;
          solve3d_2ml_options_local.tolerance_relative = real_tol / res_prev;
          solve3d_2ml_options_local.tolerance_absolute = 0.0;

          if ((solve3d_2ml_options_local.method == 0) and (::boba::norm_frobenius(sol_prev_max) > boba::epsilon<data_t>()))
          {
            solve3d_2ml_options_local.tolerance_relative /= ::boba::norm_frobenius(sol_prev_max);
          }

          checkpoint();
          auto sol_tensor = solve3d_2ml(
            Phi1mex,
            Amex,
            Phi2mex,
            rhsmex,
            real_tol * norm_rhs,
            sol_prev_max,
            solve3d_2ml_options_local);

          sol = flatten(sol_tensor);

          checkpoint();
          auto bfun3_temp = bfun3(Phi1mex, Amex, Phi2mex, sol_tensor);
          res_new = norm_difference_frobenius(bfun3_temp, rhsmex) / norm_rhs;
        }
        else
        {
          sol = sol_prev;
          res_new = res_prev;
          flg = 0;
          iter = 0;
        }
      }

      if (flg > 0)
      {
        boba_print(std::string("-warn- local solver did not converge at block ") + std::to_string(cor) + std::string("\n"));
      }
      if ((res_prev / res_new < resid_damp) and (res_new > real_tol) and ((dir + dirfilter) != 0))
      {
        boba_print("--warn-- the residual damp was smaller than in the truncation\n");
      }

      checkpoint();
      auto sol_diff = norm_difference_frobenius(sol, sol_prev);

      dx[cor] = sol_diff / ::boba::norm_frobenius(sol);
      max_dx = max(max_dx, dx[cor]);

      checkpoint();
      // The new core does not converge - increase rank
      if ((dx[cor] / dx_old[cor] > top_conv) and (dx[cor] > convergence_tolerance))
      {
        dranks[cor] = dranks[cor] + step_drank;
        dpows[cor] = dpows[cor] + step_dpow;
      }
      // The new core converges well - try to decrease rank
      if ((dx[cor] / dx_old[cor] < bot_conv) or (dx[cor] < convergence_tolerance))
      {
        dranks[cor] = (dranks[cor] > step_drank) ? (dranks[cor] - step_drank) : 0_z;
        dpows[cor] = (dpows[cor] > step_dpow + min_dpow) ? (dpows[cor] - step_dpow) : min_dpow;
      }
      if (last_sweep)
      {
        dpows[cor] = 0.5;
        dranks[cor] = 0_z;
      }
      // Error indicators
      max_res = max(max_res, res_prev);
      max_iter = max(max_iter, iter);

      // Truncation
      Matrix<space, data_t> u;
      Matrix<space, data_t> v;
      Vector<space, data_t> s_vec;
      index_t r;
      checkpoint();
      if ((dir + dirfilter) != 0)
      {
        checkpoint();
        auto rows = crx.ranks(cor) * crx.sizes(cor);
        auto cols = crx.sizes(cor + 1) * crx.ranks(cor + 2);
        auto sol_matrix = reshape_to_matrix(sol, {rows, cols});
        SVD<space, data_t> svd;
        svd(sol_matrix);
        u = svd.U;
        s_vec = svd.S;
        v = svd.V;

        checkpoint();
        // Residual trunc; First, bin-search
        auto r1 = 0_z;
        auto r2 = s_vec.size();
        r = round((r1 + r2) / 2);
        while (r2 > r1 + 1)
        {
          auto u_less = u;
          auto s_vec_less = s_vec;
          auto v_less = v;
          checkpoint();
          u_less.resize({u_less.rows(), r});
          v_less.resize({v_less.rows(), r});
          s_vec_less.resize({r});
          checkpoint();
          auto v_less_T = v_less.transpose();
          auto cursol = u_less * diagonalize(s_vec_less) * v_less_T;
          data_t res = 1.0;
          checkpoint();
          if (crx.ranks(cor) * crx.sizes(cor) * crx.sizes(cor + 1) * crx.ranks(cor + 2) < max_direct_solve_size)
          {
            auto norm_residual = norm_difference_frobenius(B * flatten(cursol), rhs_flat);
            res = norm_residual / norm_rhs;
          }
          else
          {
            auto cursol_tensor = reshape_from_matrix<4>(u_less * diagonalize(s_vec_less) * v_less_T, {crx.ranks(cor), crx.sizes(cor), crx.sizes(cor + 1), crx.ranks(cor + 2)});
            res = norm_difference_frobenius(bfun3(Phi1, A1, A2, Phi2, cursol_tensor), rhs_flat) / norm_rhs;
          }

          checkpoint();
          auto tol_pow_temp = pow(static_cast<data_t>(dimension), static_cast<data_t>(dpows[cor]));
          if (res < max(convergence_tolerance / tol_pow_temp, res_new * resid_damp))
          {
            r2 = r;
          }
          else
          {
            r1 = r;
          }
          r = round((r1 + r2) / 2);
        }

        // More accurate Linear search
        checkpoint();
        while (r <= s_vec.size())
        {
          checkpoint();
          auto u_less = u;
          auto s_vec_less = s_vec;
          auto v_less = v;
          u_less.resize({u_less.rows(), r});
          v_less.resize({v_less.rows(), r});
          s_vec_less.resize({r});
          auto v_less_T = v_less.transpose();
          auto cursol = u_less * diagonalize(s_vec_less) * v_less_T; // u(:,1:r)*diag(s(1:r))*(v(:,1:r)');

          checkpoint();
          data_t res = 1.0;
          if (crx.ranks(cor) * crx.sizes(cor) * crx.sizes(cor + 1) * crx.ranks(cor + 2) < max_direct_solve_size)
          {
            res = norm_difference_frobenius(B * flatten(cursol), rhs_flat) / norm_rhs;
          }
          else
          {
            auto cursol_tensor = reshape_from_matrix<4>(cursol, {crx.ranks(cor), crx.sizes(cor), crx.sizes(cor + 1), crx.ranks(cor + 2)});
            res = norm_difference_frobenius(bfun3(Phi1, A1, A2, Phi2, cursol_tensor), rhs_flat) / norm_rhs;
          }

          auto tol_pow_temp = pow(static_cast<data_t>(dimension), static_cast<data_t>(dpows[cor]));
          if (res < max(convergence_tolerance / tol_pow_temp, res_new * resid_damp))
          {
            break;
          }
          r = r + 1;
        }
      }
      else
      {
        if (dir > 0)
        {
          checkpoint();
          QR<space, data_t> qr;
          auto crx_mat = compute_unfold_left(crx.cores[cor]);
          qr(crx_mat);
          u = qr.Q;
          v = qr.R;
          auto crxcrx = tensor_contraction_single_index(
            {"r", "rxi+1"}, v, {"rxi+1", "ni+1", "rxi+2"}, crx.cores[cor + 1], {"rxi+2", "ni+1", "r"}); // transpose
          v = compute_unfold_left(crxcrx);
          r = u.cols();
          s_vec.resize(r);
          s_vec.fill_with(1.0);
        }
        else
        {
          checkpoint();
          QR<space, data_t> qr;
          auto crx_mat = compute_unfold_right(crx.cores[cor + 1]).transpose();
          qr(crx_mat);
          v = get_conj(qr.Q);
          u = qr.R;
          auto uT = u.conjugate_transpose();
          u = compute_unfold_left(crx.cores[cor]) * uT;
          r = u.cols();
          s_vec.resize(r);
          s_vec.fill_with(1.0);
        }
      }

      checkpoint();
      // Artificial rank increasing
      r = r + dranks[cor];
      r = min(r, s_vec.size());
      r = min(r, rmax);

      if (verb)
      {
        printf("=dmrg_solve3=   block %zu{%d}, dx: %3.3e, iter: %zu, r: %zu\n", cor, dir, dx[cor], iter, static_cast<size_t>(r));
      }

      Tensor<3, space, data_t> u_tensor;
      Tensor<3, space, data_t> v_tensor;

      if (dir > 0) //% left-to-right
      {
        checkpoint();
        u.resize({u.rows(), r});
        v.resize({v.rows(), r});
        s_vec.resize(r);
        auto v_conj = get_conj(v);
        v = v_conj * diagonalize(s_vec);

        checkpoint();
        // kick
        if ((!last_sweep) and ((dir + dirfilter) != 0))
        {
          boba::Matrix<space, data_t> u_kick({u.rows(), kickrank});
          u_kick.fill_with_random();
          auto u_kicked = boba::concatenate_columns(u, u_kick);
          QR<space, data_t> qr;
          qr(u_kicked);
          u = qr.Q;
          auto rv = qr.R;

          boba::Matrix<space, data_t> v_kick({v.rows(), kickrank});
          v_kick.fill_with_zeros();
          auto v_kicked = boba::concatenate_columns(v, v_kick);
          v = v_kicked * rv.transpose();
        }

        checkpoint();
        r = u.cols();
        u_tensor = reshape_from_matrix<3>(u, {crx.ranks(cor), crx.sizes(cor), r});
        v_tensor = reshape_from_matrix<3>(v.transpose(), {r, crx.sizes(cor + 1), crx.ranks(cor + 2)});

        // Recompute phi. Left ones, so permute them appropriately
        std::tie(phia.cores[cor + 1], std::ignore) = compute_next_Phi<dimension>(phia.cores[cor], u_tensor, crA.cores[cor], u_tensor, true, 1.0);
        std::tie(phiy.cores[cor + 1], std::ignore) = compute_next_Phi<dimension>(phiy.cores[cor], u_tensor, cry.cores[cor], true, 1.0);
      }
      else // right-to-left
      {
        checkpoint();
        u.resize({u.rows(), r});
        v.resize({v.rows(), r});
        s_vec.resize(r);
        auto u_temp = u;
        u = u_temp * diagonalize(s_vec);
        auto v_temp = v;
        v = get_conj(v_temp);

        // kick
        if ((!last_sweep) and ((dir + dirfilter) != 0))
        {
          boba::Matrix<space, data_t> v_kick({v.rows(), kickrank});
          v_kick.fill_with_random();
          auto v_kicked = boba::concatenate_columns(v, v_kick);
          QR<space, data_t> qr;
          qr(v_kicked);
          v = qr.Q;
          auto rv = qr.R;

          boba::Matrix<space, data_t> u_kick({u.rows(), kickrank});
          u_kick.fill_with_zeros();
          auto u_kicked = boba::concatenate_columns(u, u_kick);
          u = u_kicked * rv.transpose();
        }
        r = v.cols();
        u_tensor = reshape_from_matrix<3>(u, {crx.ranks(cor), crx.sizes(cor), r});
        v_tensor = reshape_from_matrix<3>(v.transpose(), {r, crx.sizes(cor + 1), crx.ranks(cor + 2)});

        // Recompute phi. Here are right phis
        std::tie(phia.cores[cor + 1], std::ignore) = compute_next_Phi<dimension>(phia.cores[cor + 2], v_tensor, crA.cores[cor + 1], v_tensor, false, 1.0);
        std::tie(phiy.cores[cor + 1], std::ignore) = compute_next_Phi<dimension>(phiy.cores[cor + 2], v_tensor, cry.cores[cor + 1], false, 1.0);
      }

      checkpoint();
      // Stuff back
      crx.cores[cor] = u_tensor;
      crx.cores[cor + 1] = v_tensor;
      boba_always_assert_equal(crx.ranks(cor + 1), r, "unexpected ranks value");

      // Check for reversal BEFORE advancing i.
      // LTR last block is i==dimension-2; RTL last block is i==0.
      // Checking after the advance caused RTL to reverse before ever visiting block (0,1).
      checkpoint();
      bool reverse = ((dir > 0) and (cor == dimension - 2)) or ((dir < 0) and (cor == 0));

      // Advance cor (clamp to avoid underflow when dir=-1 and cor=0).
      if (not reverse)
      {
        // Advance cor in the current direction.
        cor = (dir > 0) ? (cor + 1) : (cor - 1);
      }
      else
      {
        // Switch direction and reset cor to the appropriate boundary-adjacent block.
        checkpoint();
        if (verb > 0)
        {
          printf("=dmrg_solve3= sweep %zu{%d}, max_dx: %3.3e, max_res: %3.3e, max_iter: %zu, mrank: %zu\n", swp, (dir > 0) ? 1 : 0, max_dx, max_res, static_cast<size_t>(max_iter), static_cast<size_t>(max(crx.ranks())));
        }

        if (last_sweep)
        {
          break;
        }

        if (max_res < convergence_tolerance)
        {
          last_sweep = true; // comment out to test
        }

        // Reset the error indicators after the sweep
        if (((dir + dirfilter) == 0) or (dirfilter == 0))
        {
          max_res = 0;
          max_dx = 0;
          max_iter = 0;
          dx_old = dx;
        }

        checkpoint();
        swp = swp + 1;
        dir *= -1;
        // After reversing, restart from the boundary-adjacent valid block index.
        // Hitting left boundary (new dir > 0) should restart at cor=0;
        // Hitting right boundary (new dir < 0) should restart at cor=dimension-2.
        cor = (dir > 0) ? 0 : (dimension - 2);
      }
    }

    checkpoint();
    return crx;
  }
};

} // namespace boba
